import { FinancialPeriodType } from '@/types/financialReport';
import { QuarterOption, JsonRecord } from './types';

export const DONG_PER_BILLION = 1_000_000_000;

export const FIELD_LABELS: Record<string, string> = {
  balanceSheet: 'Bảng cân đối kế toán',
  incomeStatement: 'Báo cáo kết quả kinh doanh',
  cashFlowStatement: 'Báo cáo lưu chuyển tiền tệ',
  shortTermAssets: 'Tài sản ngắn hạn',
  longTermAssets: 'Tài sản dài hạn',
  bankAssets: 'Tài sản ngân hàng',
  shortTermFinancialAssets: 'Tài sản tài chính ngắn hạn',
  tradingAndCapitalAssets: 'Tài sản tự doanh và nguồn vốn',
  liabilities: 'Nợ phải trả',
  borrowings: 'Nợ vay',
  equity: 'Vốn chủ sở hữu',
  bankOperatingIncome: 'Thu nhập hoạt động ngân hàng',
  insuranceBusiness: 'Hoạt động bảo hiểm',
  securitiesRevenue: 'Doanh thu chứng khoán',
  grossProfit: 'Lợi nhuận gộp',
  expenses: 'Chi phí kinh doanh',
  profitBeforeTax: 'Lợi nhuận trước thuế',
  profitAfterTaxAndAFS: 'Lợi nhuận sau thuế và AFS',
  parentCompanyNetProfit: 'LNST công ty mẹ',
  netCashFlow: 'Lưu chuyển tiền thuần',
  operatingActivities: 'Lưu chuyển tiền từ HĐKD',
  investingActivities: 'Lưu chuyển tiền từ HĐ đầu tư',
  financingActivities: 'Lưu chuyển tiền từ HĐ tài chính',
  cash: 'Tiền và tương đương tiền',
  financialInvestments: 'Đầu tư tài chính',
  receivables: 'Các khoản phải thu',
  inventories: 'Hàng tồn kho',
  otherAssets: 'Tài sản khác',
  fixedAssets: 'Tài sản cố định',
  investmentProperty: 'Bất động sản đầu tư',
  longTermAssetsInProgress: 'Tài sản dở dang dài hạn',
  totalShortTermAssets: 'Tổng tài sản ngắn hạn',
  totalLongTermAssets: 'Tổng tài sản dài hạn',
  totalLongtTermAssets: 'Tổng tài sản dài hạn',
  loans: 'Cho vay',
  heldToMaturity: 'Nắm giữ đến ngày đáo hạn',
  availableForSale: 'Sẵn sàng để bán',
  fvtpl: 'Tài sản FVTPL',
  shortTerm: 'Nợ ngắn hạn',
  longTerm: 'Nợ dài hạn',
  shortTermBorrowings: 'Vay ngắn hạn',
  longTermBorrowings: 'Vay dài hạn',
  contributedCapital: 'Vốn góp',
  retainedEarnings: 'Lợi nhuận sau thuế chưa phân phối',
  treasuryShares: 'Cổ phiếu quỹ',
  otherCapital: 'Vốn khác',
  netInterestIncome: 'Thu nhập lãi thuần',
  serviceFeeIncome: 'Thu nhập dịch vụ',
  tradingIncome: 'Thu nhập kinh doanh',
  otherIncome: 'Thu nhập khác',
  operatingProfit: 'Lợi nhuận hoạt động',
  netOperatingRevenue: 'Doanh thu thuần hoạt động',
  operatingExpenses: 'Chi phí hoạt động',
  brokerageAndCustodyRevenue: 'Doanh thu môi giới và lưu ký',
  lendingRevenue: 'Doanh thu cho vay',
  tradingAndCapitalRevenue: 'Doanh thu tự doanh và nguồn vốn',
  investmentBankingRevenue: 'Doanh thu ngân hàng đầu tư',
  netRevenue: 'Doanh thu thuần',
  costOfGoodsSold: 'Giá vốn hàng bán',
  interestExpenses: 'Chi phí lãi vay',
  sellingExpenses: 'Chi phí bán hàng',
  financialExpenses: 'Chi phí tài chính',
  managementExpenses: 'Chi phí quản lý doanh nghiệp',
  financialProfit: 'Lợi nhuận tài chính',
  shareProfitOfAssociatesAndJoint: 'Lợi nhuận từ công ty liên kết/liên doanh',
  otherProfit: 'Lợi nhuận khác',
  provisionExpenses: 'Chi phí dự phòng',
  profitAfterTaxAndAfs: 'Lợi nhuận sau thuế và AFS',
  afsGains: 'Lãi từ AFS',
  corporateIncomeTax: 'Thuế thu nhập doanh nghiệp',
  minorityInterests: 'Lợi ích cổ đông thiểu số',
  depositsAtCentralBank: 'Tiền gửi tại NHNN',
  depositsAtOtherCreditInstitutions: 'Tiền gửi tại TCTD khác',
  tradingSecurities: 'Chứng khoán kinh doanh',
  loansToCustomers: 'Cho vay khách hàng',
  investmentSecurities: 'Chứng khoán đầu tư',
};

export const QUARTER_OPTIONS: QuarterOption[] = [
  { value: FinancialPeriodType.FirstQuarter, label: 'Quý 1' },
  { value: FinancialPeriodType.SecondQuarter, label: 'Quý 2' },
  { value: FinancialPeriodType.ThirdQuarter, label: 'Quý 3' },
  { value: FinancialPeriodType.FourthQuarter, label: 'Quý 4' },
  { value: FinancialPeriodType.YearToDate, label: 'Cả năm' },
];

export const DEFAULT_FINANCIAL_REPORT_DATA_TEMPLATE: JsonRecord = {
  balanceSheet: {
    shortTermAssets: {
      cash: null,
      financialInvestments: null,
      receivables: null,
      inventories: null,
      otherAssets: null,
      totalShortTermAssets: null,
    },
    longTermAssets: {
      receivables: null,
      fixedAssets: null,
      investmentProperty: null,
      longTermAssetsInProgress: null,
      financialInvestments: null,
      otherAssets: null,
      totalLongTermAssets: null,
      totalLongtTermAssets: null,
    },
    bankAssets: {
      depositsAtCentralBank: null,
      depositsAtOtherCreditInstitutions: null,
      tradingSecurities: null,
      loansToCustomers: null,
      investmentSecurities: null,
      otherAssets: null,
    },
    shortTermFinancialAssets: {
      cash: null,
      loans: null,
      other: null,
    },
    tradingAndCapitalAssets: {
      heldToMaturity: null,
      availableForSale: null,
      fvtpl: null,
    },
    liabilities: {
      shortTerm: null,
      longTerm: null,
    },
    borrowings: {
      shortTermBorrowings: null,
      longTermBorrowings: null,
    },
    equity: {
      contributedCapital: null,
      retainedEarnings: null,
      treasuryShares: null,
      otherCapital: null,
    },
  },
  incomeStatement: {
    bankOperatingIncome: {
      netInterestIncome: null,
      serviceFeeIncome: null,
      tradingIncome: null,
      otherIncome: null,
    },
    insuranceBusiness: {
      operatingProfit: null,
      netOperatingRevenue: null,
      operatingExpenses: null,
    },
    securitiesRevenue: {
      brokerageAndCustodyRevenue: null,
      lendingRevenue: null,
      tradingAndCapitalRevenue: null,
      investmentBankingRevenue: null,
    },
    grossProfit: {
      netRevenue: null,
      costOfGoodsSold: null,
      grossProfit: null,
    },
    expenses: {
      interestExpenses: null,
      sellingExpenses: null,
      financialExpenses: null,
      managementExpenses: null,
    },
    profitBeforeTax: {
      operatingProfit: null,
      financialProfit: null,
      shareProfitOfAssociatesAndJoint: null,
      otherProfit: null,
      profitBeforeTax: null,
    },
    profitAfterTaxAndAFS: {
      profitAfterTaxAndAfs: null,
      afsGains: null,
    },
    parentCompanyNetProfit: {
      profitBeforeTax: null,
      corporateIncomeTax: null,
      minorityInterests: null,
      parentCompanyNetProfit: null,
    },
  },
  cashFlowStatement: {
    netCashFlow: null,
    operatingActivities: null,
    investingActivities: null,
    financingActivities: null,
  },
};
